import type { NextPage } from 'next'
import Head from 'next/head'
import UseTranslation from 'next-translate/useTranslation'

const Home: NextPage = () => {
  const { t } = UseTranslation('home')
  return (
    <div>
      <Head>
        <title>Air Language</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </div>
  )
}

export default Home
