import type { NextPage } from 'next'
import Head from 'next/head'
import UseTranslation from 'next-translate/useTranslation'

const Home: NextPage = () => {
  const { t } = UseTranslation('home')
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>KURWA</main>
      {t('title')}
    </div>
  )
}

export default Home
